"""add hr domain: jobs, candidates, resumes, processing jobs, assessments, screenings, interviews, schedule slots

Revision ID: 09ffcd4d02d8
Revises: 2789ab740c22
Create Date: 2026-08-19 11:33:09.011438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ffcd4d02d8'
down_revision: Union[str, None] = '2789ab740c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', name='employmenttype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='jobstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_jobs_organization_id'), 'hr_jobs', ['organization_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('resume_upload', 'manual', 'referral', name='candidatesource', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('stage', sa.Enum('new', 'processing', 'matched', 'hr_review', 'screening_approved', 'screening', 'screened', 'human_review', 'interview_pending', 'interview_scheduled', 'completed', 'rejected', 'withdrawn', 'on_hold', name='candidatestage', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('resume_id', sa.String(length=40), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['hr_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_job_id'), 'candidates', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidates_organization_id'), 'candidates', ['organization_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('jd_match', name='assessmentkind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_match', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_match', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('missing_requirements', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_candidate_id'), 'assessments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessments_organization_id'), 'assessments', ['organization_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'validating', 'stored', 'ocr_processing', 'parsing', 'extracting', 'normalizing', 'matching', 'completed', 'processing_failed', 'extraction_failed', 'matching_failed', name='resumeprocessingstatus', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_organization_id'), 'resumes', ['organization_id'], unique=False)
    op.create_table('schedule_slots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('interviewer_user_id', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interviewer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_slots_interviewer_user_id'), 'schedule_slots', ['interviewer_user_id'], unique=False)
    op.create_index(op.f('ix_schedule_slots_organization_id'), 'schedule_slots', ['organization_id'], unique=False)
    op.create_table('screenings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='screeningstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('external_call_ref', sa.String(length=120), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_candidate_id'), 'screenings', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_screenings_organization_id'), 'screenings', ['organization_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=False),
    sa.Column('screening_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'scheduled', 'completed', 'cancelled', name='interviewstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('scheduled_slot_id', sa.String(length=40), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('interviewer_user_id', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_slot_id'], ['schedule_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_organization_id'), 'interviews', ['organization_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('resume_id', sa.String(length=40), nullable=False),
    sa.Column('job_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='processingjobstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_organization_id'), 'processing_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_resume_id'), 'processing_jobs', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_resume_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_organization_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_interviews_organization_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_screenings_organization_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_candidate_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_schedule_slots_organization_id'), table_name='schedule_slots')
    op.drop_index(op.f('ix_schedule_slots_interviewer_user_id'), table_name='schedule_slots')
    op.drop_table('schedule_slots')
    op.drop_index(op.f('ix_resumes_organization_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_assessments_organization_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_candidate_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_candidates_organization_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_job_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_hr_jobs_organization_id'), table_name='hr_jobs')
    op.drop_table('hr_jobs')
    # ### end Alembic commands ###
