"""add leads, voice projects and requirements

Revision ID: 2789ab740c22
Revises: ce4ec6e434cc
Create Date: 2026-08-19 11:27:16.761157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2789ab740c22'
down_revision: Union[str, None] = 'ce4ec6e434cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('demo_request', 'voice_customization', 'hr_sales_request', name='leadtype', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'converted', 'rejected', name='leadstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_contact_email'), 'leads', ['contact_email'], unique=False)
    op.create_table('voice_projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('lead_created', 'discovery', 'requirements_collected', 'configuration', 'integration', 'testing', 'customer_approval', 'deployment_pending', 'active', 'configuration_failed', 'integration_failed', 'deployment_failed', name='voiceprojectstatus', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('assigned_engineer_user_id', sa.String(length=40), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_projects_lead_id'), 'voice_projects', ['lead_id'], unique=False)
    op.create_index(op.f('ix_voice_projects_organization_id'), 'voice_projects', ['organization_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('voice_project_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_project_id'], ['voice_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_voice_project_id'), 'requirements', ['voice_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirements_voice_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_voice_projects_organization_id'), table_name='voice_projects')
    op.drop_index(op.f('ix_voice_projects_lead_id'), table_name='voice_projects')
    op.drop_table('voice_projects')
    op.drop_index(op.f('ix_leads_contact_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
