"""add jaan voice credit ledger recharge orders and packages

Revision ID: 40b17faa83f4
Revises: 355bc75d3eb5
Create Date: 2026-09-18 15:36:09.677137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '40b17faa83f4'
down_revision: Union[str, None] = '355bc75d3eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_recharge_packages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_recharge_orders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('package_id', sa.String(length=40), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'cancelled', 'refunded', name='rechargeorderstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_checkout_session_id', sa.String(length=160), nullable=True),
    sa.Column('provider_payment_reference', sa.String(length=160), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['voice_recharge_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_recharge_orders_organization_id'), 'voice_recharge_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voice_recharge_orders_provider_checkout_session_id'), 'voice_recharge_orders', ['provider_checkout_session_id'], unique=False)
    op.create_table('voice_credit_transactions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('initial_allocation', 'usage_debit', 'recharge', 'complimentary', 'admin_adjustment', 'refund', name='credittransactiontype', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('recharge_order_id', sa.String(length=40), nullable=True),
    sa.Column('call_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recharge_order_id'], ['voice_recharge_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', name='uq_voice_credit_txn_call_id')
    )
    op.create_index(op.f('ix_voice_credit_transactions_organization_id'), 'voice_credit_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voice_credit_transactions_recharge_order_id'), 'voice_credit_transactions', ['recharge_order_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected an unrelated pre-existing drift
    # (document_chunks.embedding: JSON -> VECTOR(1536)) between the
    # DocumentChunk model and this DB — out of scope for Jaan Voice
    # Credits, deliberately excluded from this migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_credit_transactions_recharge_order_id'), table_name='voice_credit_transactions')
    op.drop_index(op.f('ix_voice_credit_transactions_organization_id'), table_name='voice_credit_transactions')
    op.drop_table('voice_credit_transactions')
    op.drop_index(op.f('ix_voice_recharge_orders_provider_checkout_session_id'), table_name='voice_recharge_orders')
    op.drop_index(op.f('ix_voice_recharge_orders_organization_id'), table_name='voice_recharge_orders')
    op.drop_table('voice_recharge_orders')
    op.drop_table('voice_recharge_packages')
    # ### end Alembic commands ###
