"""add_voice_call_usage_table

Revision ID: 5768cee4e704
Revises: c72a8cd585be
Create Date: 2026-08-19 13:04:05.470230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5768cee4e704'
down_revision: Union[str, None] = 'c72a8cd585be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_usages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('stt_seconds', sa.Integer(), nullable=False),
    sa.Column('tts_characters', sa.Integer(), nullable=False),
    sa.Column('telephony_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_call_usages_organization_id'), 'call_usages', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_usages_organization_id'), table_name='call_usages')
    op.drop_table('call_usages')
    # ### end Alembic commands ###
