"""add hr calendar integrations and resume extracted profile

Revision ID: 6fa9e91b5b63
Revises: 09ffcd4d02d8
Create Date: 2026-08-19 11:48:56.988656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa9e91b5b63'
down_revision: Union[str, None] = '09ffcd4d02d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_type', sa.Enum('user', 'aivra_admin', 'system', name='actortype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=60), nullable=False),
    sa.Column('result', sa.Enum('success', 'failure', name='auditresult', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('request_id', sa.String(length=60), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('hr_calendar_integrations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.Enum('google_calendar', name='integrationprovider', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_calendar_integrations_organization_id'), 'hr_calendar_integrations', ['organization_id'], unique=False)
    op.add_column('resumes', sa.Column('extracted_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_profile')
    op.drop_index(op.f('ix_hr_calendar_integrations_organization_id'), table_name='hr_calendar_integrations')
    op.drop_table('hr_calendar_integrations')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
