"""add interview candidate notified at

Revision ID: 7b97bc420dbb
Revises: 84e570d611b5
Create Date: 2026-08-20 12:46:49.158238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7b97bc420dbb'
down_revision: Union[str, None] = '84e570d611b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'interviews', sa.Column('candidate_notified_at', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'candidate_notified_at')
    # ### end Alembic commands ###
