"""add hr screening voice fields interview panelists job company name

Revision ID: 84e570d611b5
Revises: 298020f7dcf3
Create Date: 2026-08-20 12:25:47.958942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '84e570d611b5'
down_revision: Union[str, None] = '298020f7dcf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_panelists',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('interview_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_panelists_interview_id'), 'interview_panelists', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_panelists_organization_id'), 'interview_panelists', ['organization_id'], unique=False)
    op.add_column('hr_jobs', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('screenings', sa.Column('prompt_text', sa.Text(), nullable=True))
    op.add_column('screenings', sa.Column('prompt_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('screenings', sa.Column('prompt_edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('screenings', sa.Column('prompt_edited_by_user_id', sa.String(length=40), nullable=True))
    op.add_column('screenings', sa.Column('prompt_history', sa.JSON(), nullable=True))
    op.add_column('screenings', sa.Column('livekit_room_name', sa.String(length=120), nullable=True))
    op.add_column('screenings', sa.Column('livekit_dispatch_id', sa.String(length=120), nullable=True))
    op.add_column('screenings', sa.Column('sip_call_participant_identity', sa.String(length=120), nullable=True))
    op.add_column('screenings', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('screenings', sa.Column('transcript', sa.JSON(), nullable=True))
    op.add_column('screenings', sa.Column('result', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'result')
    op.drop_column('screenings', 'transcript')
    op.drop_column('screenings', 'failure_reason')
    op.drop_column('screenings', 'sip_call_participant_identity')
    op.drop_column('screenings', 'livekit_dispatch_id')
    op.drop_column('screenings', 'livekit_room_name')
    op.drop_column('screenings', 'prompt_history')
    op.drop_column('screenings', 'prompt_edited_by_user_id')
    op.drop_column('screenings', 'prompt_edited_at')
    op.drop_column('screenings', 'prompt_generated_at')
    op.drop_column('screenings', 'prompt_text')
    op.drop_column('hr_jobs', 'company_name')
    op.drop_index(op.f('ix_interview_panelists_organization_id'), table_name='interview_panelists')
    op.drop_index(op.f('ix_interview_panelists_interview_id'), table_name='interview_panelists')
    op.drop_table('interview_panelists')
    # ### end Alembic commands ###
