"""add knowledge module: sources, source versions, document chunks with pgvector

Revision ID: b04ab831f230
Revises: 6fa9e91b5b63
Create Date: 2026-08-19 12:20:37.572417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b04ab831f230'
down_revision: Union[str, None] = '6fa9e91b5b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('knowledge_collections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_collections_organization_id'), 'knowledge_collections', ['organization_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('collection_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('file', 'url', 'connected_source', name='sourcetype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('syncing', 'synced', 'failed', 'stale', name='sourcestatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('owner_user_id', sa.String(length=40), nullable=False),
    sa.Column('employee_access', sa.JSON(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['knowledge_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_organization_id'), 'knowledge_sources', ['organization_id'], unique=False)
    op.create_table('source_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('knowledge_source_id', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('validating', 'uploading', 'extracting', 'normalizing', 'chunking', 'embedding', 'storing', 'indexing', 'ready', 'failed', name='sourceprocessingstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_versions_knowledge_source_id'), 'source_versions', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_source_versions_organization_id'), 'source_versions', ['organization_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('knowledge_source_id', sa.String(length=40), nullable=False),
    sa.Column('source_version_id', sa.String(length=40), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_knowledge_source_id'), 'document_chunks', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_version_id'), 'document_chunks', ['source_version_id'], unique=False)
    # ANN index for cosine-distance similarity search (see
    # DocumentChunkRepository.similarity_search). HNSW over ivfflat: builds
    # incrementally without needing training data present at creation time.
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_source_version_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_knowledge_source_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_source_versions_organization_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_knowledge_source_id'), table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index(op.f('ix_knowledge_sources_organization_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_knowledge_collections_organization_id'), table_name='knowledge_collections')
    op.drop_table('knowledge_collections')
    # ### end Alembic commands ###
