"""add voice domain: telephony, tools, agents, agent versions, calls, transcripts, recordings, analysis

Revision ID: c72a8cd585be
Revises: b04ab831f230
Create Date: 2026-08-19 12:28:39.956559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72a8cd585be'
down_revision: Union[str, None] = 'b04ab831f230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_records_organization_id'), 'compliance_records', ['organization_id'], unique=False)
    op.create_table('dnd_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dnd_entries_organization_id'), 'dnd_entries', ['organization_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('condition', sa.Enum('business_hours', 'after_hours', 'region', 'agent_unavailable', name='routingcondition', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_organization_id'), 'routing_rules', ['organization_id'], unique=False)
    op.create_table('telephony_provider_accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('provider_type', sa.Enum('twilio', 'plivo', 'exotel', 'tata_tele', 'sip_byoc', name='telephonyprovidertype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('account_label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('connected', 'not_connected', name='telephonyaccountstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telephony_provider_accounts_organization_id'), 'telephony_provider_accounts', ['organization_id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('kind', sa.Enum('api', 'transfer', 'internal', name='toolkind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', name='toolmethod', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('auth_type', sa.Enum('none', 'api_key', 'bearer', name='toolauthtype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_organization_id'), 'tools', ['organization_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('provider_account_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'unassigned', 'porting', name='phonenumberstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_account_id'], ['telephony_provider_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_numbers_organization_id'), 'phone_numbers', ['organization_id'], unique=False)
    op.create_table('sip_trunks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider_account_id', sa.String(length=40), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='siptrunkstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('codec', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_account_id'], ['telephony_provider_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sip_trunks_organization_id'), 'sip_trunks', ['organization_id'], unique=False)
    op.create_table('voice_agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('draft', 'testing', 'live', 'paused', name='voiceagentstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('environment', sa.Enum('staging', 'production', name='voiceagentenvironment', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('assigned_phone_number_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_agents_organization_id'), 'voice_agents', ['organization_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('voice_agent_id', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'test', 'approved', 'published', 'archived', name='agentversionstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('prompt_config', sa.JSON(), nullable=False),
    sa.Column('flow_config', sa.JSON(), nullable=False),
    sa.Column('context_config', sa.JSON(), nullable=False),
    sa.Column('library', sa.JSON(), nullable=False),
    sa.Column('tool_ids', sa.JSON(), nullable=False),
    sa.Column('voice_config', sa.JSON(), nullable=False),
    sa.Column('transcription_config', sa.JSON(), nullable=False),
    sa.Column('call_end_config', sa.JSON(), nullable=False),
    sa.Column('transfer_config', sa.JSON(), nullable=False),
    sa.Column('analysis_config', sa.JSON(), nullable=False),
    sa.Column('call_actions_config', sa.JSON(), nullable=False),
    sa.Column('advanced_config', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_agent_id'], ['voice_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_versions_organization_id'), 'agent_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_versions_voice_agent_id'), 'agent_versions', ['voice_agent_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('voice_agent_id', sa.String(length=40), nullable=False),
    sa.Column('agent_version_id', sa.String(length=40), nullable=False),
    sa.Column('provider_call_id', sa.String(length=120), nullable=True),
    sa.Column('room_name', sa.String(length=255), nullable=True),
    sa.Column('caller_name', sa.String(length=255), nullable=True),
    sa.Column('caller_number', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='calldirection', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', name='callstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('faq', 'booking', 'cancellation', 'status_lookup', 'complaint', 'unknown', name='callintent', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('outcome', sa.Enum('resolved', 'booked', 'cancelled', 'escalated', 'no_action', 'failed', name='calloutcome', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('recording_available', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_agent_id'], ['voice_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_organization_id'), 'calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_calls_voice_agent_id'), 'calls', ['voice_agent_id'], unique=False)
    op.create_table('call_analyses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('intent_detected', sa.String(length=120), nullable=True),
    sa.Column('sentiment', sa.String(length=30), nullable=True),
    sa.Column('resolution_status', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_call_analyses_organization_id'), 'call_analyses', ['organization_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_events_organization_id'), 'call_events', ['organization_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'available', 'failed', name='recordingstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_recordings_organization_id'), 'recordings', ['organization_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('tool_id', sa.String(length=40), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'pending', 'timeout', name='toolexecutionstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_call_id'), 'tool_executions', ['call_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_organization_id'), 'tool_executions', ['organization_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=40), nullable=False),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_transcripts_organization_id'), 'transcripts', ['organization_id'], unique=False)
    # NOTE: autogenerate wanted to drop+recreate ix_document_chunks_embedding_hnsw
    # here because it was created via raw op.execute() in b04ab831f230 and is
    # invisible to SQLAlchemy model metadata. Removed both — leaving it alone
    # is correct; dropping it in upgrade() would have actually destroyed it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_organization_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_tool_executions_organization_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_call_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_recordings_organization_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_call_events_organization_id'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_call_analyses_organization_id'), table_name='call_analyses')
    op.drop_table('call_analyses')
    op.drop_index(op.f('ix_calls_voice_agent_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_organization_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_agent_versions_voice_agent_id'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_organization_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_voice_agents_organization_id'), table_name='voice_agents')
    op.drop_table('voice_agents')
    op.drop_index(op.f('ix_sip_trunks_organization_id'), table_name='sip_trunks')
    op.drop_table('sip_trunks')
    op.drop_index(op.f('ix_phone_numbers_organization_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_tools_organization_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_telephony_provider_accounts_organization_id'), table_name='telephony_provider_accounts')
    op.drop_table('telephony_provider_accounts')
    op.drop_index(op.f('ix_routing_rules_organization_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_dnd_entries_organization_id'), table_name='dnd_entries')
    op.drop_table('dnd_entries')
    op.drop_index(op.f('ix_compliance_records_organization_id'), table_name='compliance_records')
    op.drop_table('compliance_records')
    # ### end Alembic commands ###
