"""add hr job ai agent name

Revision ID: e31e62e7c0ab
Revises: 7b97bc420dbb
Create Date: 2026-08-20 17:11:11.911170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e31e62e7c0ab'
down_revision: Union[str, None] = '7b97bc420dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_jobs', sa.Column('ai_agent_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_jobs', 'ai_agent_name')
    # ### end Alembic commands ###
